import { clsx } from "clsx";
import { twMerge } from "tailwind-merge";

export function cn(...inputs) {
  return twMerge(clsx(inputs));
}

export const colleges = [
  {
    name: "BHAGALPUR COLLEGE OF ENGINEERING",
    shortName: "bce-bhagalpur",
    college_id: "001",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent facilisis dui ut magna hendrerit, non fermentum justo pharetra. Sed venenatis quam non orci interdum, in consequat ex sodales. Nullam id turpis nec eros bibendum dictum ac a magna. Vivamus porttitor, eros eget interdum molestie, risus nisi cursus dolor, et euismod velit erat a risus. Duis nec gravida libero, vel faucibus odio. Ut malesuada sem et lectus tincidunt, sit amet dictum metus viverra. Nam vel metus eget urna tristique posuere non in arcu. Suspendisse sit amet felis at magna vehicula fermentum.Curabitur sagittis varius lectus, nec interdum sapien iaculis vel. Fusce ac ligula sem. Vestibulum egestas sodales lacus. Aenean auctor nunc sed tellus dignissim, nec suscipit lacus tempus. Vivamus venenatis volutpat libero, vel efficitur ante fringilla sit amet. Sed in erat at lorem iaculis gravida. Proin ac risus eu risus iaculis ultrices. Maecenas posuere mi vitae velit ultricies posuere. Nulla luctus est ac nibh auctor, ut tincidunt justo pretium. Quisque posuere consequat elit, eget egestas sapien finibus sed. Suspendisse potenti. Pellentesque fringilla, nisl ut ultrices sagittis, eros arcu lacinia eros, vel accumsan purus odio at metus.",
    students: [
      {
        id: 1,
        name: "Arjun Mehta",
        branch: "Computer Science",
        year: "2nd Year",
        grade: "A",
        cgpa: 9.2,
      },
      {
        id: 2,
        name: "Priya Sharma",
        branch: "Electronics and Communication",
        year: "3rd Year",
        grade: "B+",
        cgpa: 8.5,
      },
      {
        id: 3,
        name: "Rohan Gupta",
        branch: "Mechanical Engineering",
        year: "4th Year",
        grade: "A-",
        cgpa: 7.8,
      },
      {
        id: 4,
        name: "Sana Khan",
        branch: "Information Technology",
        year: "1st Year",
        grade: "A+",
        cgpa: 9.7,
      },
      {
        id: 5,
        name: "Neha Verma",
        branch: "Civil Engineering",
        year: "3rd Year",
        grade: "B",
        cgpa: 6.9,
      },
      {
        id: 6,
        name: "Vikram Singh",
        branch: "Electrical Engineering",
        year: "2nd Year",
        grade: "A",
        cgpa: 8.8,
      },
      {
        id: 7,
        name: "Ishaan Choudhary",
        branch: "Aerospace Engineering",
        year: "4th Year",
        grade: "A+",
        cgpa: 9.5,
      },
      {
        id: 8,
        name: "Meera Kapoor",
        branch: "Biotechnology",
        year: "2nd Year",
        grade: "B+",
        cgpa: 7.6,
      },
      {
        id: 9,
        name: "Ankit Yadav",
        branch: "Chemical Engineering",
        year: "3rd Year",
        grade: "A",
        cgpa: 8.3,
      },
      {
        id: 10,
        name: "Tara Joshi",
        branch: "Data Science",
        year: "1st Year",
        grade: "A+",
        cgpa: 9.8,
      },
    ],
    faculties: [
      {
        id: 1,
        name: "Dr. Rajesh Gupta",
        department: "Computer Science",
        designation: "Professor",
        experience: 15,
        rating: 9.3,
        profileImage: "https://example.com/images/rajesh-gupta.jpg",
        email: "rajesh.gupta@university.edu",
        phone: "+1-234-567-8901",
        office: "Room 101, CS Building",
        specialization: "Artificial Intelligence, Machine Learning",
        courses: ["Introduction to AI", "Advanced Machine Learning"],
      },
      {
        id: 2,
        name: "Ms. Anjali Verma",
        department: "Electronics and Communication",
        designation: "Assistant Professor",
        experience: 8,
        rating: 8.7,
        profileImage: "https://example.com/images/anjali-verma.jpg",
        email: "anjali.verma@university.edu",
        phone: "+1-234-567-8902",
        office: "Room 202, EC Building",
        specialization: "Signal Processing, Wireless Communication",
        courses: ["Digital Communication", "Signal Processing Fundamentals"],
      },
      {
        id: 3,
        name: "Dr. Vikram Rao",
        department: "Mechanical Engineering",
        designation: "Professor",
        experience: 20,
        rating: 9.6,
        profileImage: "https://example.com/images/vikram-rao.jpg",
        email: "vikram.rao@university.edu",
        phone: "+1-234-567-8903",
        office: "Room 303, ME Building",
        specialization: "Thermodynamics, Fluid Mechanics",
        courses: ["Thermodynamics", "Fluid Dynamics"],
      },
      {
        id: 4,
        name: "Dr. Meena Kapoor",
        department: "Information Technology",
        designation: "Associate Professor",
        experience: 12,
        rating: 8.9,
        profileImage: "https://example.com/images/meena-kapoor.jpg",
        email: "meena.kapoor@university.edu",
        phone: "+1-234-567-8904",
        office: "Room 104, IT Building",
        specialization: "Database Systems, Data Security",
        courses: ["Database Management", "Cybersecurity Basics"],
      },
      {
        id: 5,
        name: "Mr. Arvind Mishra",
        department: "Civil Engineering",
        designation: "Assistant Professor",
        experience: 6,
        rating: 7.8,
        profileImage: "https://example.com/images/arvind-mishra.jpg",
        email: "arvind.mishra@university.edu",
        phone: "+1-234-567-8905",
        office: "Room 205, CE Building",
        specialization: "Structural Engineering, Geotechnical Engineering",
        courses: ["Structural Analysis", "Geotechnical Engineering"],
      },
      {
        id: 6,
        name: "Dr. Preeti Sharma",
        department: "Electrical Engineering",
        designation: "Professor",
        experience: 18,
        rating: 9.4,
        profileImage: "https://example.com/images/preeti-sharma.jpg",
        email: "preeti.sharma@university.edu",
        phone: "+1-234-567-8906",
        office: "Room 306, EE Building",
        specialization: "Power Systems, Renewable Energy",
        courses: ["Power Systems Analysis", "Renewable Energy Technology"],
      },
      {
        id: 7,
        name: "Dr. Ravi Shankar",
        department: "Aerospace Engineering",
        designation: "Professor",
        experience: 25,
        rating: 9.8,
        profileImage: "https://example.com/images/ravi-shankar.jpg",
        email: "ravi.shankar@university.edu",
        phone: "+1-234-567-8907",
        office: "Room 401, AE Building",
        specialization: "Aerodynamics, Propulsion Systems",
        courses: ["Aerodynamics", "Aircraft Propulsion"],
      },
      {
        id: 8,
        name: "Ms. Sonia Das",
        department: "Biotechnology",
        designation: "Assistant Professor",
        experience: 5,
        rating: 7.5,
        profileImage: "https://example.com/images/sonia-das.jpg",
        email: "sonia.das@university.edu",
        phone: "+1-234-567-8908",
        office: "Room 108, BT Building",
        specialization: "Genetic Engineering, Molecular Biology",
        courses: ["Molecular Biology", "Genetic Engineering Principles"],
      },
      {
        id: 9,
        name: "Dr. Karan Mehta",
        department: "Chemical Engineering",
        designation: "Associate Professor",
        experience: 10,
        rating: 8.5,
        profileImage: "https://example.com/images/karan-mehta.jpg",
        email: "karan.mehta@university.edu",
        phone: "+1-234-567-8909",
        office: "Room 207, ChE Building",
        specialization: "Chemical Process Design, Thermodynamics",
        courses: ["Process Design", "Chemical Thermodynamics"],
      },
      {
        id: 10,
        name: "Dr. Neha Joshi",
        department: "Data Science",
        designation: "Professor",
        experience: 14,
        rating: 9.2,
        profileImage: "https://example.com/images/neha-joshi.jpg",
        email: "neha.joshi@university.edu",
        phone: "+1-234-567-8910",
        office: "Room 110, DS Building",
        specialization: "Big Data Analytics, Machine Learning",
        courses: ["Big Data Fundamentals", "Introduction to Machine Learning"],
      },
      {
        id: 11,
        name: "Dr. Roshni Joshi",
        department: "Data Science",
        designation: "Professor",
        experience: 14,
        rating: 9.2,
        profileImage: "https://example.com/images/neha-joshi.jpg",
        email: "neha.joshi@university.edu",
        phone: "+1-234-567-8910",
        office: "Room 110, DS Building",
        specialization: "Big Data Analytics, Machine Learning",
        courses: ["Big Data Fundamentals", "Introduction to Machine Learning"],
      },
    ],
  },
  {
    name: "GAYA COLLEGE OF ENGINEERING",
    shortName: "gce-gaya",
    college_id: "002",
    description:
      "Gaya College of Engineering offers a range of technical programs in engineering. The campus is equipped with state-of-the-art infrastructure and provides students with hands-on experience.",
    students: [
      {
        id: 1,
        name: "Aman Dubey",
        branch: "Computer Science",
        year: "1st Year",
        grade: "A+",
        cgpa: 9.5,
      },
      {
        id: 2,
        name: "Kritika Sharma",
        branch: "Information Technology",
        year: "2nd Year",
        grade: "A",
        cgpa: 8.9,
      },
      {
        id: 3,
        name: "Varun Patel",
        branch: "Mechanical Engineering",
        year: "3rd Year",
        grade: "B+",
        cgpa: 7.4,
      },
      {
        id: 4,
        name: "Isha Aggarwal",
        branch: "Civil Engineering",
        year: "4th Year",
        grade: "A",
        cgpa: 8.7,
      },
      {
        id: 5,
        name: "Rajat Verma",
        branch: "Electronics and Communication",
        year: "1st Year",
        grade: "A-",
        cgpa: 7.9,
      },
      {
        id: 6,
        name: "Neha Kapoor",
        branch: "Electrical Engineering",
        year: "3rd Year",
        grade: "B",
        cgpa: 6.5,
      },
      {
        id: 7,
        name: "Aditya Kumar",
        branch: "Aerospace Engineering",
        year: "4th Year",
        grade: "A+",
        cgpa: 9.3,
      },
      {
        id: 8,
        name: "Riya Singh",
        branch: "Biotechnology",
        year: "2nd Year",
        grade: "B+",
        cgpa: 7.6,
      },
      {
        id: 9,
        name: "Nikhil Joshi",
        branch: "Chemical Engineering",
        year: "3rd Year",
        grade: "A",
        cgpa: 8.4,
      },
      {
        id: 10,
        name: "Tanvi Chauhan",
        branch: "Data Science",
        year: "1st Year",
        grade: "A+",
        cgpa: 9.7,
      },
    ],
  },
  {
    name: "DARBHANGA COLLEGE OF ENGINEERING",
    shortName: "dce-darbhanga",
    college_id: "003",
    description:
      "Darbhanga College of Engineering provides quality education in engineering disciplines. The college emphasizes on overall development through extracurricular activities and workshops.",

    students: [
      {
        id: 1,
        name: "Arjun Mehta",
        branch: "Computer Science",
        year: "2nd Year",
        grade: "A",
        cgpa: 8,
      },
      {
        id: 2,
        name: "Priya Sharma",
        branch: "Electronics and Communication",
        year: "3rd Year",
        grade: "B+",
        cgpa: 9,
      },
      {
        id: 3,
        name: "Rohan Gupta",
        branch: "Mechanical Engineering",
        year: "4th Year",
        grade: "A-",
        cgpa: 7.5,
      },
      {
        id: 4,
        name: "Sana Khan",
        branch: "Information Technology",
        year: "1st Year",
        grade: "A+",
        cgpa: 8.2,
      },
      {
        id: 5,
        name: "Neha Verma",
        branch: "Civil Engineering",
        year: "3rd Year",
        grade: "B",
        cgpa: 9,
      },
      {
        id: 6,
        name: "Vikram Singh",
        branch: "Electrical Engineering",
        year: "2nd Year",
        grade: "A",
        cgpa: 7.9,
      },
      {
        id: 7,
        name: "Ishaan Choudhary",
        branch: "Aerospace Engineering",
        year: "4th Year",
        grade: "A+",
        cgpa: 9,
      },
      {
        id: 8,
        name: "Meera Kapoor",
        branch: "Biotechnology",
        year: "2nd Year",
        grade: "B+",
        cgpa: 7,
      },
      {
        id: 9,
        name: "Ankit Yadav",
        branch: "Chemical Engineering",
        year: "3rd Year",
        grade: "A",
        cgpa: 9.5,
      },
      {
        id: 10,
        name: "Tara Joshi",
        branch: "Data Science",
        year: "1st Year",
        grade: "A+",
        cgpa: 8.9,
      },
    ],
  },
  {
    name: "MOTIHARI COLLEGE OF ENGINEERING",
    shortName: "mce-motihari",
    college_id: "004",
    description:
      "Motihari College of Engineering offers a diverse range of engineering programs. It is known for its academic excellence and collaborative research initiatives with industry partners.",

    students: [
      {
        id: 1,
        name: "Arjun Mehta",
        branch: "Computer Science",
        year: "2nd Year",
        grade: "A",
      },
      {
        id: 2,
        name: "Priya Sharma",
        branch: "Electronics and Communication",
        year: "3rd Year",
        grade: "B+",
      },
      {
        id: 3,
        name: "Rohan Gupta",
        branch: "Mechanical Engineering",
        year: "4th Year",
        grade: "A-",
      },
      {
        id: 4,
        name: "Sana Khan",
        branch: "Information Technology",
        year: "1st Year",
        grade: "A+",
      },
      {
        id: 5,
        name: "Neha Verma",
        branch: "Civil Engineering",
        year: "3rd Year",
        grade: "B",
      },
      {
        id: 6,
        name: "Vikram Singh",
        branch: "Electrical Engineering",
        year: "2nd Year",
        grade: "A",
      },
      {
        id: 7,
        name: "Ishaan Choudhary",
        branch: "Aerospace Engineering",
        year: "4th Year",
        grade: "A+",
      },
      {
        id: 8,
        name: "Meera Kapoor",
        branch: "Biotechnology",
        year: "2nd Year",
        grade: "B+",
      },
      {
        id: 9,
        name: "Ankit Yadav",
        branch: "Chemical Engineering",
        year: "3rd Year",
        grade: "A",
      },
      {
        id: 10,
        name: "Tara Joshi",
        branch: "Data Science",
        year: "1st Year",
        grade: "A+",
      },
    ],
  },
  {
    name: "LOK NAYAK JAI PRAKASH INSTITUTE OF TECHNOLOGY",
    shortName: "lnjpit-chapra",
    college_id: "005",
    description:
      "LNJPIT offers a wide range of technical programs, focusing on industry-oriented skills. The college promotes research activities and has excellent lab facilities.",

    students: [
      {
        id: 1,
        name: "Arjun Mehta",
        branch: "Computer Science",
        year: "2nd Year",
        grade: "A",
      },
      {
        id: 2,
        name: "Priya Sharma",
        branch: "Electronics and Communication",
        year: "3rd Year",
        grade: "B+",
      },
      {
        id: 3,
        name: "Rohan Gupta",
        branch: "Mechanical Engineering",
        year: "4th Year",
        grade: "A-",
      },
      {
        id: 4,
        name: "Sana Khan",
        branch: "Information Technology",
        year: "1st Year",
        grade: "A+",
      },
      {
        id: 5,
        name: "Neha Verma",
        branch: "Civil Engineering",
        year: "3rd Year",
        grade: "B",
      },
      {
        id: 6,
        name: "Vikram Singh",
        branch: "Electrical Engineering",
        year: "2nd Year",
        grade: "A",
      },
      {
        id: 7,
        name: "Ishaan Choudhary",
        branch: "Aerospace Engineering",
        year: "4th Year",
        grade: "A+",
      },
      {
        id: 8,
        name: "Meera Kapoor",
        branch: "Biotechnology",
        year: "2nd Year",
        grade: "B+",
      },
      {
        id: 9,
        name: "Ankit Yadav",
        branch: "Chemical Engineering",
        year: "3rd Year",
        grade: "A",
      },
      {
        id: 10,
        name: "Tara Joshi",
        branch: "Data Science",
        year: "1st Year",
        grade: "A+",
      },
    ],
  },
  {
    name: "SERSHAH ENGINEERING COLLEGE",
    shortName: "sec-sasaram",
    college_id: "006",
    description:
      "Sershah Engineering College focuses on producing high-quality engineers by providing modern teaching methods, industry internships, and a strong placement record.",

    students: [
      {
        id: 1,
        name: "Arjun Mehta",
        branch: "Computer Science",
        year: "2nd Year",
        grade: "A",
      },
      {
        id: 2,
        name: "Priya Sharma",
        branch: "Electronics and Communication",
        year: "3rd Year",
        grade: "B+",
      },
      {
        id: 3,
        name: "Rohan Gupta",
        branch: "Mechanical Engineering",
        year: "4th Year",
        grade: "A-",
      },
      {
        id: 4,
        name: "Sana Khan",
        branch: "Information Technology",
        year: "1st Year",
        grade: "A+",
      },
      {
        id: 5,
        name: "Neha Verma",
        branch: "Civil Engineering",
        year: "3rd Year",
        grade: "B",
      },
      {
        id: 6,
        name: "Vikram Singh",
        branch: "Electrical Engineering",
        year: "2nd Year",
        grade: "A",
      },
      {
        id: 7,
        name: "Ishaan Choudhary",
        branch: "Aerospace Engineering",
        year: "4th Year",
        grade: "A+",
      },
      {
        id: 8,
        name: "Meera Kapoor",
        branch: "Biotechnology",
        year: "2nd Year",
        grade: "B+",
      },
      {
        id: 9,
        name: "Ankit Yadav",
        branch: "Chemical Engineering",
        year: "3rd Year",
        grade: "A",
      },
      {
        id: 10,
        name: "Tara Joshi",
        branch: "Data Science",
        year: "1st Year",
        grade: "A+",
      },
    ],
  },
  {
    name: "RASHTRAKAVI RAMDHARI SINGH DINKAR COLLEGE OF ENGINEERING",
    shortName: "rrsdce-begusarai",
    college_id: "007",
    description:
      "The college provides world-class education in the field of engineering and technology. Students receive hands-on training and are encouraged to participate in innovative projects.",
    students: [
      {
        id: 1,
        name: "Arjun Mehta",
        branch: "Computer Science",
        year: "2nd Year",
        grade: "A",
      },
      {
        id: 2,
        name: "Priya Sharma",
        branch: "Electronics and Communication",
        year: "3rd Year",
        grade: "B+",
      },
      {
        id: 3,
        name: "Rohan Gupta",
        branch: "Mechanical Engineering",
        year: "4th Year",
        grade: "A-",
      },
      {
        id: 4,
        name: "Sana Khan",
        branch: "Information Technology",
        year: "1st Year",
        grade: "A+",
      },
      {
        id: 5,
        name: "Neha Verma",
        branch: "Civil Engineering",
        year: "3rd Year",
        grade: "B",
      },
      {
        id: 6,
        name: "Vikram Singh",
        branch: "Electrical Engineering",
        year: "2nd Year",
        grade: "A",
      },
      {
        id: 7,
        name: "Ishaan Choudhary",
        branch: "Aerospace Engineering",
        year: "4th Year",
        grade: "A+",
      },
      {
        id: 8,
        name: "Meera Kapoor",
        branch: "Biotechnology",
        year: "2nd Year",
        grade: "B+",
      },
      {
        id: 9,
        name: "Ankit Yadav",
        branch: "Chemical Engineering",
        year: "3rd Year",
        grade: "A",
      },
      {
        id: 10,
        name: "Tara Joshi",
        branch: "Data Science",
        year: "1st Year",
        grade: "A+",
      },
    ],
  },
  {
    name: "SUPAUL COLLEGE OF ENGINEERING",
    shortName: "sce-supaul",
    college_id: "008",
    description:
      "Supaul College of Engineering offers undergraduate programs in engineering with an emphasis on research, practical training, and skill development.",
    students: [
      {
        id: 1,
        name: "Arjun Mehta",
        branch: "Computer Science",
        year: "2nd Year",
        grade: "A",
      },
      {
        id: 2,
        name: "Priya Sharma",
        branch: "Electronics and Communication",
        year: "3rd Year",
        grade: "B+",
      },
      {
        id: 3,
        name: "Rohan Gupta",
        branch: "Mechanical Engineering",
        year: "4th Year",
        grade: "A-",
      },
      {
        id: 4,
        name: "Sana Khan",
        branch: "Information Technology",
        year: "1st Year",
        grade: "A+",
      },
      {
        id: 5,
        name: "Neha Verma",
        branch: "Civil Engineering",
        year: "3rd Year",
        grade: "B",
      },
      {
        id: 6,
        name: "Vikram Singh",
        branch: "Electrical Engineering",
        year: "2nd Year",
        grade: "A",
      },
      {
        id: 7,
        name: "Ishaan Choudhary",
        branch: "Aerospace Engineering",
        year: "4th Year",
        grade: "A+",
      },
      {
        id: 8,
        name: "Meera Kapoor",
        branch: "Biotechnology",
        year: "2nd Year",
        grade: "B+",
      },
      {
        id: 9,
        name: "Ankit Yadav",
        branch: "Chemical Engineering",
        year: "3rd Year",
        grade: "A",
      },
      {
        id: 10,
        name: "Tara Joshi",
        branch: "Data Science",
        year: "1st Year",
        grade: "A+",
      },
    ],
  },
  {
    name: "BAKHTIYARPUR COLLEGE OF ENGINEERING",
    shortName: "bce-bakhtiyarpur",
    college_id: "009",
    description:
      "Bakhtiyarpur College of Engineering is known for its strong academic programs and infrastructure. It focuses on developing students' technical skills and research capabilities.",
    students: [
      {
        id: 1,
        name: "Arjun Mehta",
        branch: "Computer Science",
        year: "2nd Year",
        grade: "A",
      },
      {
        id: 2,
        name: "Priya Sharma",
        branch: "Electronics and Communication",
        year: "3rd Year",
        grade: "B+",
      },
      {
        id: 3,
        name: "Rohan Gupta",
        branch: "Mechanical Engineering",
        year: "4th Year",
        grade: "A-",
      },
      {
        id: 4,
        name: "Sana Khan",
        branch: "Information Technology",
        year: "1st Year",
        grade: "A+",
      },
      {
        id: 5,
        name: "Neha Verma",
        branch: "Civil Engineering",
        year: "3rd Year",
        grade: "B",
      },
      {
        id: 6,
        name: "Vikram Singh",
        branch: "Electrical Engineering",
        year: "2nd Year",
        grade: "A",
      },
      {
        id: 7,
        name: "Ishaan Choudhary",
        branch: "Aerospace Engineering",
        year: "4th Year",
        grade: "A+",
      },
      {
        id: 8,
        name: "Meera Kapoor",
        branch: "Biotechnology",
        year: "2nd Year",
        grade: "B+",
      },
      {
        id: 9,
        name: "Ankit Yadav",
        branch: "Chemical Engineering",
        year: "3rd Year",
        grade: "A",
      },
      {
        id: 10,
        name: "Tara Joshi",
        branch: "Data Science",
        year: "1st Year",
        grade: "A+",
      },
    ],
  },
  {
    name: "SITAMARHI INSTITUTE OF TECHNOLOGY",
    shortName: "sit-sitamarhi",
    college_id: "010",
    description:
      "Sitamarhi Institute of Technology offers specialized engineering education with an emphasis on technology-driven innovations and industry collaborations.",
  },
  {
    name: "PURNEA COLLEGE OF ENGINEERING",
    shortName: "pce-purnea",
    college_id: "011",
    description:
      "Purnea College of Engineering is committed to providing high-quality engineering education. It has a vibrant campus life and a strong focus on research and development.",
  },
  {
    name: "B. P. MANDAL COLLEGE OF ENGINEERING",
    shortName: "bpcm-madhepura",
    college_id: "012",
    description:
      "BP Mandal College of Engineering offers cutting-edge engineering programs. It focuses on innovation and offers numerous opportunities for student growth and development.",
  },
  {
    name: "KATIHAR ENGINEERING COLLEGE",
    shortName: "keck-katihar",
    college_id: "013",
    description:
      "Katihar Engineering College focuses on providing high-quality technical education with a strong emphasis on industry interaction and modern teaching methods.",
  },
  {
    name: "SAHARSA COLLEGE OF ENGINEERING",
    shortName: "sce-saharsa",
    college_id: "014",
    description:
      "Saharsha College of Engineering offers a variety of engineering courses. The college strives for excellence in teaching, research, and overall student development.",
  },
  {
    name: "GOVERNMENT ENGINEERING COLLEGE, JAMUI",
    shortName: "gec-jamui",
    college_id: "015",
    description:
      "Government Engineering College, Jamui, is a state-run institution providing quality engineering education. It offers modern infrastructure and a well-developed research ecosystem.",
  },
  {
    name: "GOVERNMENT ENGINEERING COLLEGE, BANKA",
    shortName: "gec-banka",
    college_id: "016",
    description:
      "Government Engineering College, Banka, provides state-of-the-art facilities and focuses on fostering industry-ready engineers with a practical learning approach.",
  },
  {
    name: "GOVERNMENT ENGINEERING COLLEGE, VAISHALI",
    shortName: "gec-vaishali",
    college_id: "017",
    description:
      "Government Engineering College, Vaishali offers undergraduate engineering courses with an emphasis on quality education, research, and innovation.",
  },
  {
    name: "GOVERNMENT ENGINEERING COLLEGE, NAWADA",
    shortName: "gec-nawada",
    college_id: "018",
    description:
      "Government Engineering College, Nawada offers programs that are designed to develop students' technical skills and knowledge with cutting-edge infrastructure.",
  },
  {
    name: "GOVERNMENT ENGINEERING COLLEGE, KISHANGANJ",
    shortName: "gec-kishanganj",
    college_id: "019",
    description:
      "Government Engineering College, Kishanganj is known for its academic excellence and innovative teaching methods. It prepares students for global engineering challenges.",
  },
  {
    name: "GOVERNMENT ENGINEERING COLLEGE, MUNGER",
    shortName: "gec-munger",
    college_id: "020",
    description:
      "Government Engineering College, Munger offers cutting-edge courses in engineering, ensuring students are well-prepared for both industry and academia.",
  },
  // Continue adding other colleges similarly...
];
